
name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Checkout
    runs-on: ubuntu-latest
      steps: - name: Install SSH key
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
      - uses: actions/checkout@v2
        with:
          ref: demo
      - run: npm install
      - run: npm run build -- --configuration production --aot --base-href /acal-app-v3/
      - run: rsync -r --delete-after dist/. "${{ secrets.REMOTE_URL }}":"${{ secrets.ADDRESS }}"
